# Generated by Django 5.2.17 on 2026-09-12 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodflow', '0007_moodentry_animations'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranSurah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran_id', models.PositiveSmallIntegerField(unique=True)),
                ('name_arabic', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('name_transliteration', models.CharField(max_length=100)),
                ('verses_count', models.PositiveSmallIntegerField()),
                ('revelation_place', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciter_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MoodSurahRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('calm', 'Calm'), ('focused', 'Focused'), ('tired', 'Tired'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('excited', 'Excited')], max_length=50)),
                ('reason', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_recommendations', to='moodflow.quransurah')),
            ],
        ),
        migrations.CreateModel(
            name='QuranSurahAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciter_id', models.PositiveIntegerField()),
                ('reciter_name', models.CharField(max_length=255)),
                ('audio_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='moodflow.quransurah')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('surah', 'reciter_id'), name='unique_surah_reciter_audio')],
            },
        ),
    ]
