# Generated by Django 5.2.17 on 2026-09-20 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodflow', '0008_quransurah_reciter_moodsurahrecommendation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quransurahaudio',
            name='unique_surah_reciter_audio',
        ),
        migrations.RemoveField(
            model_name='quransurahaudio',
            name='reciter_id',
        ),
        migrations.RemoveField(
            model_name='quransurahaudio',
            name='reciter_name',
        ),
        migrations.AddField(
            model_name='quransurahaudio',
            name='reciter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='moodflow.reciter'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='quransurahaudio',
            constraint=models.UniqueConstraint(fields=('surah', 'reciter'), name='unique_surah_reciter_audio'),
        ),
    ]
