# Generated by Django 5.2.17 on 2026-10-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodflow', '0009_remove_quransurahaudio_unique_surah_reciter_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
